% copy and paste these commands into the field 'icon drawing commands' of the block mask: 
% right-click on block -> 'Mask' -> 'Edit Mask' -> 'Mask Editor' -> 'Icons & Ports'

port_label('input', 1, 'Ts')
port_label('input', 2, 'velocity_')
port_label('input', 3, 'velocity_dot')
port_label('input', 4, 'x')
port_label('input', 5, 'y')
port_label('input', 6, 'x_dot')
port_label('input', 7, 'y_dot')
port_label('input', 8, 'Delta_u')
port_label('input', 9, 'Delta_u_dot')
port_label('input', 10, 'async_input_data_valid')
port_label('input', 11, 'input_sample_valid')
port_label('input', 12, 'd_sample')
port_label('input', 13, 'x_sample')
port_label('input', 14, 'y_sample')
port_label('input', 15, 'psi_sample')
port_label('input', 16, 'K_sample')
port_label('output', 1, 'output_valid')
port_label('output', 2, 'need_more_path_input_data')
port_label('output', 3, 'distance_at_the_end_of_horizon')
port_label('output', 4, 'distance_ahead')
port_label('output', 5, 'head_index')
port_label('output', 6, 'read_position')
port_label('output', 7, 'elements_free_to_write')
port_label('output', 8, 'tracked_index')
port_label('output', 9, 'd_star')
port_label('output', 10, 'v_star')
port_label('output', 11, 'x_r')
port_label('output', 12, 'y_r')
port_label('output', 13, 'psi_r')
port_label('output', 14, 'K_r')
port_label('output', 15, 'psi_r_dot')
port_label('output', 16, 'Delta_l')
port_label('output', 17, 'Delta_l_dot')
