#!/bin/bash
set -e

pip install jupyter-server-proxy

# python setup.py install
pip install .


cd ~
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest

