#!/bin/bash
set -e

cd ~

echo "----------- installing jupyter extension ----------"
pip install jupyter-server-proxy
jupyter labextension install @jupyterlab/server-proxy

# python setup.py install

pip install .


git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest

